export const BLOG_CONFIG = {
  NOTION_PAGE_ID: process.env.NOTION_PAGE_ID,
  NOTION_TOKEN: process.env.NOTION_TOKEN,
  NAVER_SITE_VERIFICATION: process.env.NAVER_SITE_VERIFICATION,
  GOOGLE_MEASUREMENT_ID: process.env.GOOGLE_MEASUREMENT_ID,
  NEXT_PUBLIC_SITE_URL: process.env.__NEXT_PRIVATE_ORIGIN ?? 'http://localhost:3000',
};
