export function plural(count:number,singular:string,pluralForm?:string):string;
export function compactRange(start:string,end:string):string;
export function meetingSummary(window:{startDate:string;endDate:string;startTime:string;endTime:string;timezone:string}):string;
export function dayLabel(date:string):string;
export function saveStatus(input:{state:string;dirty:boolean;edited:boolean}):{tone:'idle'|'saving'|'saved'|'error';text:string};
export function fillButtonLabel(count:number):string;
export function fillToast(count:number,removed?:number):string;
export function memberInvitedLine(isRecipient:boolean|null,organizer?:string):string;
export function invitationsSentToast(count:number):string;
export function resendQuestion(count:number|undefined):string;
export const MEETING_TOASTS:Readonly<{linkCopied:string;copyFailed:string;renamed:string;nameUpdated:string;editSaved:string;resent:string;saveFailed:string;scheduleSaved:string;deleted:string}>;
export function shortDay(date:string):string;
export function confirmedWhen(input:{date:string;start:string;end:string;timezone:string}):string;
export function confirmedChip(confirmation:{startsAt:string;endsAt?:string;timezone:string}|null|undefined):string;
export const RSVP_LABELS:Readonly<{accepted:string;declined:string;tentative:string;needsAction:string}>;
export function rsvpSummary(counts:{accepted:number;declined:number;tentative:number;needsAction:number}):string;
export function bestTimeLine(window:{count:number;total:number;missing:string[]}):string;
export function dayTime(input:{date:string;start?:string;end?:string}):string;
export function scheduleWarning(impact:{removedSlots:number;people:string[]},confirmed:boolean):string;
export function deleteMeetingCopy(title:string,confirmed:boolean):{title:string;description:string};
export function loadErrorTitle(title?:string|null):string;
export function organizedBy(name?:string|null):string;
export const MEETING_COPY:Readonly<{titleLabel:string;titlePlaceholder:string;titleError:string;peopleHeading:string;organizerBadge:string;reviewDescription:string;send:string;sendRetry:string;noLongerWorks:string;bestTimes:string;scheduleHeading:string;deleteMeeting:string;deleteHint:string;deleteConfirm:string;deleting:string;invitationHeading:string;loadErrorDetail:string;reconnect:string;reconnectPrompt:string}>;
import type {WwmLocale,WwmTranslate} from '../../i18n/wwm.mjs';
export type MeetingCopy={
 t:WwmTranslate;locale:WwmLocale;
 compactRange:typeof compactRange;meetingSummary:typeof meetingSummary;dayLabel:typeof dayLabel;shortDay:typeof shortDay;
 confirmedWhen:typeof confirmedWhen;confirmedChip:typeof confirmedChip;RSVP_LABELS:typeof RSVP_LABELS;rsvpSummary:typeof rsvpSummary;
 saveStatus:typeof saveStatus;fillButtonLabel:typeof fillButtonLabel;fillToast:typeof fillToast;memberInvitedLine:typeof memberInvitedLine;
 invitationsSentToast:typeof invitationsSentToast;resendQuestion:typeof resendQuestion;MEETING_TOASTS:typeof MEETING_TOASTS;
 bestTimeLine:typeof bestTimeLine;dayTime:typeof dayTime;scheduleWarning:typeof scheduleWarning;deleteMeetingCopy:typeof deleteMeetingCopy;
 loadErrorTitle:typeof loadErrorTitle;organizedBy:typeof organizedBy;MEETING_COPY:typeof MEETING_COPY;
 /** Dictionary message for a failed request (by HTTP status and situation). */
 apiError:(error:unknown,situation:'create'|'join'|'rename'|'schedule'|'delete')=>string;
};
export function createMeetingCopy(locale?:string):MeetingCopy;
