'use client';
import './async-region.css';
import './room-skeleton.css';
import {LoadingState} from './LoadingState';
import WallBackLink from '@/container/light-wall/WallBackLink';
import {useWwmCopy} from './i18n/WwmI18nProvider';
export function MeetingRowsSkeleton(){const {t}=useWwmCopy();return <section className="wwm-card wwm-meetings" role="status" aria-label={t('list.loadingShort')}><LoadingState label={t('list.loading')} description={t('room.findingTimes')}/>{[0,1].map(i=><div key={i} className="wwm-skeleton-meeting"><span/><span/></div>)}</section>}
export function AvailabilitySkeleton({days=7,rows=12}:{days?:number;rows?:number}){const {t}=useWwmCopy();const columns=Array.from({length:Math.max(1,days)},(_,i)=>i);return <section className="wwm-card wwm-availability wwm-skeleton-availability" aria-busy="true" aria-label={t('room.loadingAvailability')}><div className="wwm-skeleton-status"><LoadingState label={t('room.loadingAvailability')}/></div><div className="wwm-skeleton-view-tabs" aria-hidden="true">{[0,1,2,3].map(i=><span key={i}/>)}</div><div className="wwm-skeleton-toolbar" aria-hidden="true"><span/><span/></div><div className="wwm-skeleton-legend" aria-hidden="true"><span/><span/></div><div className="wwm-skeleton-calendar" aria-hidden="true" style={{'--wwm-skeleton-days':columns.length} as React.CSSProperties}><div className="wwm-skeleton-date-row"><i/>{columns.map(i=><div key={i}><span/><span/></div>)}</div>{Array.from({length:rows},(_,i)=><div className="wwm-skeleton-time-row" key={i}><i>{i%2===0&&<span/>}</i>{columns.map(day=><div key={day}/>)}</div>)}</div></section>}
export function RoomSkeleton(){const {t}=useWwmCopy();return <><div className="wwm-topline"><WallBackLink href="/craft/when-we-meet">{t('app.meetings')}</WallBackLink></div><div className="wwm-shell"><header className="wwm-skeleton-room-header" aria-label={t('room.loading')} aria-busy="true"><div className="wwm-skeleton-room-heading" aria-hidden="true"><span/><span/></div><div className="wwm-skeleton-actions" aria-hidden="true"><span/><span/></div></header><AvailabilitySkeleton/></div></>}
