export const GA_MEASUREMENT_ID = 'G-07RYXQL1X0';

export const ANALYTICS_EVENTS = {
  WEB_VITAL: 'web_vital',
  PAGE_LOAD: 'page_load',
  UI_CLICK: 'ui_click',
  UI_INPUT: 'ui_input',
  SEARCH_RESULTS: 'search_results',
  GALLERY_VIEW: 'gallery_view',
  UI_CHANGE: 'ui_change',
  UI_INTERACTION: 'ui_interaction',
  UI_EXPAND: 'ui_expand',
  FORM_SUBMIT: 'form_submit',
  WWM_OUTCOME: 'wwm_outcome',
  WWM_FUNNEL: 'wwm_funnel',
  WWM_EXIT: 'wwm_exit',
  CONTENT_SCROLL: 'content_scroll',
  ENVIRONMENT_BROWSER: 'environment_browser',
  ENVIRONMENT_DEVICE: 'environment_device',
  ENVIRONMENT_NETWORK: 'environment_network',
} as const;

export const ANALYTICS_ACTIONS = {
  SEARCH_OPEN: 'search_open',
  SEARCH_CLOSE: 'search_close',
  SEARCH_RESULT_ACTIVATE: 'search_result_activate',
  SEARCH_RESULTS_FOCUS: 'search_results_focus',
  MENU_CLOSE: 'menu_close',
  POST_NAVIGATE: 'post_navigate',
  GALLERY_NAVIGATE: 'gallery_navigate',
  GALLERY_CLOSE: 'gallery_close',
  COLOR_MODE_CHANGE: 'color_mode_change',
  DESIGN_CHANGE: 'design_change',
  ARTICLE_IMAGE_OPEN: 'article_image_open',
  ARTICLE_IMAGE_CLOSE: 'article_image_close',
  MEDIA_PLAY: 'media_play',
  MEDIA_PAUSE: 'media_pause',
  MEDIA_COMPLETE: 'media_complete',
  MEDIA_SEEK: 'media_seek',
  MEDIA_VOLUME: 'media_volume',
} as const;

/** When We Meet operations reported by `wwm_outcome` (result of the server call, not the click). */
export const ANALYTICS_WWM_OPERATIONS = {
  SIGN_IN_START: 'sign_in_start',
  CALENDAR_CONNECT_START: 'calendar_connect_start',
  CALENDAR_CONNECT_RETURN: 'calendar_connect_return',
  CREATE_ROOM: 'create_room',
  JOIN_ROOM: 'join_room',
  SAVE_RESPONSE: 'save_response',
  CALENDAR_BUSY: 'calendar_busy',
  CONFIRM_SEND: 'confirm_send',
  CONFIRM_UPDATE: 'confirm_update',
  CONFIRM_RESEND: 'confirm_resend',
  RENAME_ROOM: 'rename_room',
  UPDATE_SCHEDULE: 'update_schedule',
  DELETE_ROOM: 'delete_room',
  INVITATION_PREVIEW: 'invitation_preview',
  LOAD_MEETINGS: 'load_meetings',
  LOAD_ROOM: 'load_room',
  LOAD_CONFIRMATION: 'load_confirmation',
} as const;

/**
 * When We Meet funnels, in the order a person moves through them. `step_index` in `wwm_funnel` is the position here,
 * so the last step reached before `wwm_exit` shows where people drop off. Signals are side events (errors, tab views)
 * that do not advance a funnel.
 */
export const ANALYTICS_WWM_FUNNELS = {
  /** Landing on /craft/when-we-meet: guest → sign-in → signed-in list. */
  onboarding: ['guest_view', 'sign_in_click', 'list_view'],
  /** Creating a meeting: dialog → typed → required fields → submitted → created. */
  create: ['dialog_open', 'first_input', 'title_filled', 'dates_filled', 'name_filled', 'submit', 'created', 'invite_copied'],
  /** Invitee: link opened → signed in → joined. */
  invite: ['landing_view', 'sign_in_click', 'signed_in', 'join_submit', 'joined'],
  /** Anyone inside a room: opened → picked times → saved. */
  room: ['room_view', 'first_select', 'first_saved'],
  /** Organizer on the Confirm tab: opened → picked a time → reviewed → sent. */
  confirm: ['tab_view', 'time_selected', 'review_open', 'sent'],
} as const;

export type AnalyticsWwmFlow = keyof typeof ANALYTICS_WWM_FUNNELS;
export type AnalyticsWwmStep<F extends AnalyticsWwmFlow> = (typeof ANALYTICS_WWM_FUNNELS)[F][number];

export const ANALYTICS_WWM_SIGNALS = {
  VALIDATION_ERROR: 'validation_error',
  SUBMIT_FAILED: 'submit_failed',
  JOIN_FAILED: 'join_failed',
  SAVE_FAILED: 'save_failed',
  WENT_OFFLINE: 'went_offline',
  TAB_VIEW: 'tab_view',
  INVITE_COPY: 'invite_copy',
  SETTINGS_OPEN: 'settings_open',
  CALENDAR_FILL_APPLIED: 'calendar_fill_applied',
  REVIEW_BACK: 'review_back',
  LOGIN_PROMPT: 'login_prompt',
} as const;

export type AnalyticsWwmSignal = (typeof ANALYTICS_WWM_SIGNALS)[keyof typeof ANALYTICS_WWM_SIGNALS];

export type AnalyticsWwmOperation = (typeof ANALYTICS_WWM_OPERATIONS)[keyof typeof ANALYTICS_WWM_OPERATIONS];
export type AnalyticsEvent = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
export type AnalyticsAction = (typeof ANALYTICS_ACTIONS)[keyof typeof ANALYTICS_ACTIONS];

export const ANALYTICS_ELEMENTS = {
  HOME_LINK: 'home_link',
  NAV_LINK: 'nav_link',
  POST_OPEN: 'post_open',
  POST_BACK: 'post_back',
  SEARCH_OPEN: 'search_open',
  SEARCH_CLOSE: 'search_close',
  SEARCH_CLEAR: 'search_clear',
  SEARCH_INPUT: 'search_input',
  SEARCH_RESULT: 'search_result',
  SEARCH_FORM: 'search_form',
  MENU_OPEN: 'menu_open',
  MENU_CLOSE: 'menu_close',
  COLOR_MODE_TOGGLE: 'color_mode_toggle',
  DESIGN_SELECT: 'design_select',
  LANGUAGE_SELECT: 'language_select',
  GALLERY_OPEN: 'gallery_open',
  GALLERY_PREVIOUS: 'gallery_previous',
  GALLERY_NEXT: 'gallery_next',
  GALLERY_CLOSE: 'gallery_close',
  GALLERY_LOCATION: 'gallery_location',
  GALLERY_RETRY: 'gallery_retry',
  CONTACT_LINK: 'contact_link',
  PROJECT_LINK: 'project_link',
  RESUME_LINK: 'resume_link',
  DESIGN_ABOUT: 'design_about',
  DESIGN_PREVIEW: 'design_preview',
  FOOTER_LINK: 'footer_link',
  POST_PREVIOUS: 'post_previous',
  POST_NEXT: 'post_next',
  ARTICLE_LINK: 'article_link',
  ARTICLE_TOGGLE: 'article_toggle',
  ARTICLE_IMAGE: 'article_image',
  ARTICLE_IMAGE_CLOSE: 'article_image_close',
  ARTICLE_BUTTON: 'article_button',
  ARTICLE_COPY: 'article_copy',
  EMBED_OPEN: 'embed_open',
  MEDIA_CONTROL: 'media_control',
  // Shared product controls (Craft, error pages). Labels are fixed UI names, never user data.
  BACK_LINK: 'back_link',
  RETRY: 'retry',
  TEXT_INPUT: 'text_input',
  SIGN_IN: 'sign_in',
  DIALOG_CANCEL: 'dialog_cancel',
  DIALOG_DONE: 'dialog_done',
  AUTH_RETURN: 'auth_return',
  CRAFT_PROJECT: 'craft_project',
  CRAFT_LEGAL_LINK: 'craft_legal_link',
  CRAFT_LEGAL_CONTACT: 'craft_legal_contact',
  CRAFT_LEGAL_EXTERNAL: 'craft_legal_external',
  // When We Meet. Room IDs, names, emails and titles are never attached as ids or labels.
  MEETING_OPEN: 'meeting_open',
  MEETING_NEW: 'meeting_new',
  MEETING_CREATE_FORM: 'meeting_create_form',
  MEETING_CREATE_SUBMIT: 'meeting_create_submit',
  MEETING_TITLE_INPUT: 'meeting_title_input',
  MEETING_NAME_INPUT: 'meeting_name_input',
  MEETING_RENAME_INPUT: 'meeting_rename_input',
  MEETING_JOIN: 'meeting_join',
  MEETING_SETTINGS: 'meeting_settings',
  MEETING_SETTINGS_FORM: 'meeting_settings_form',
  MEETING_TAB: 'meeting_tab',
  MEETING_MENU: 'meeting_menu',
  INVITE_LINK_COPY: 'invite_link_copy',
  INVITE_LINK_INPUT: 'invite_link_input',
  DATE_RANGE_PICKER: 'date_range_picker',
  DATE_PICKER: 'date_picker',
  DATE_OPTION: 'date_option',
  MONTH_PREVIOUS: 'month_previous',
  MONTH_NEXT: 'month_next',
  TIME_PICKER: 'time_picker',
  TIME_OPTION: 'time_option',
  ALL_DAY_TOGGLE: 'all_day_toggle',
  TIMEZONE_PICKER: 'timezone_picker',
  TIMEZONE_SEARCH: 'timezone_search',
  TIMEZONE_OPTION: 'timezone_option',
  FIELD_TRIGGER: 'field_trigger',
  COMMAND_INPUT: 'command_input',
  COMMAND_ITEM: 'command_item',
  AVAILABILITY_CELL: 'availability_cell',
  AVAILABILITY_BLOCK: 'availability_block',
  CALENDAR_COMPACT: 'calendar_compact',
  CALENDAR_DAY_PAGER: 'calendar_day_pager',
  CALENDAR_SHOW_EARLIER: 'calendar_show_earlier',
  CALENDAR_FILL: 'calendar_fill',
  CALENDAR_FILL_APPLY: 'calendar_fill_apply',
  CALENDAR_FILL_DISMISS: 'calendar_fill_dismiss',
  CALENDAR_CONNECT: 'calendar_connect',
  CONFIRM_CELL: 'confirm_cell',
  CONFIRM_REVIEW: 'confirm_review',
  CONFIRM_RECIPIENT: 'confirm_recipient',
  CONFIRM_RECIPIENT_OPTIONAL: 'confirm_recipient_optional',
  CONFIRM_EVENT_TITLE: 'confirm_event_title',
  CONFIRM_SEND: 'confirm_send',
  CONFIRM_CHECK_AGAIN: 'confirm_check_again',
  CONFIRM_EVENT_LINK: 'confirm_event_link',
  CONFIRM_EDIT: 'confirm_edit',
  CONFIRM_EDIT_SAVE: 'confirm_edit_save',
  CONFIRM_EDIT_CANCEL: 'confirm_edit_cancel',
  CONFIRM_RESEND: 'confirm_resend',
  CONFIRM_RESEND_SEND: 'confirm_resend_send',
  CONFIRM_MANUAL_TIME: 'confirm_manual_time',
  CONFIRM_SHOW_AVAILABILITY: 'confirm_show_availability',
} as const;

export const ANALYTICS_SECTIONS = {
  HEADER: 'header',
  NAV_DOCK: 'nav_dock',
  MENU: 'menu',
  POST_LIST: 'post_list',
  SEARCH: 'search',
  ARTICLE: 'article',
  GALLERY: 'gallery',
  GALLERY_VIEWER: 'gallery_viewer',
  ABOUT_HERO: 'about_hero',
  ABOUT_PROJECTS: 'about_projects',
  ABOUT_CONTACT: 'about_contact',
  RESUME_CONTACT: 'resume_contact',
  RESUME_PROJECTS: 'resume_projects',
  DESIGN_PICKER: 'design_picker',
  DESIGN_STORY: 'design_story',
  FOOTER: 'footer',
  ERROR: 'error',
  CRAFT_PROJECTS: 'craft_projects',
  CRAFT_LEGAL: 'craft_legal',
  CRAFT_ACCOUNT: 'craft_account',
  WWM_AUTH: 'wwm_auth',
  WWM_MEETINGS: 'wwm_meetings',
  WWM_CREATE: 'wwm_create',
  WWM_INVITATION: 'wwm_invitation',
  WWM_ROOM: 'wwm_room',
  WWM_AVAILABILITY: 'wwm_availability',
  WWM_PEOPLE: 'wwm_people',
  WWM_CONFIRM: 'wwm_confirm',
} as const;

export const ANALYTICS_PAGES = {
  HOME: 'home',
  POST: 'post',
  ABOUT: 'about',
  RESUME: 'resume',
  GALLERY: 'gallery',
  PERSONAL: 'personal',
  DESIGNS: 'designs',
  ABOUT_DESIGN: 'about_design',
  UNKNOWN: 'unknown',
} as const;
