export const GA_MEASUREMENT_ID = 'G-07RYXQL1X0';

export const ANALYTICS_EVENTS = {
  WEB_VITAL: 'web_vital',
  PAGE_LOAD: 'page_load',
  UI_CLICK: 'ui_click',
  UI_INPUT: 'ui_input',
  SEARCH_RESULTS: 'search_results',
  GALLERY_VIEW: 'gallery_view',
  UI_CHANGE: 'ui_change',
  UI_INTERACTION: 'ui_interaction',
  UI_EXPAND: 'ui_expand',
  FORM_SUBMIT: 'form_submit',
  CONTENT_SCROLL: 'content_scroll',
  ENVIRONMENT_BROWSER: 'environment_browser',
  ENVIRONMENT_DEVICE: 'environment_device',
  ENVIRONMENT_NETWORK: 'environment_network',
} as const;

export const ANALYTICS_ACTIONS = {
  SEARCH_OPEN: 'search_open',
  SEARCH_CLOSE: 'search_close',
  SEARCH_RESULT_ACTIVATE: 'search_result_activate',
  SEARCH_RESULTS_FOCUS: 'search_results_focus',
  MENU_CLOSE: 'menu_close',
  POST_NAVIGATE: 'post_navigate',
  GALLERY_NAVIGATE: 'gallery_navigate',
  GALLERY_CLOSE: 'gallery_close',
  COLOR_MODE_CHANGE: 'color_mode_change',
  DESIGN_CHANGE: 'design_change',
  ARTICLE_IMAGE_OPEN: 'article_image_open',
  ARTICLE_IMAGE_CLOSE: 'article_image_close',
  MEDIA_PLAY: 'media_play',
  MEDIA_PAUSE: 'media_pause',
  MEDIA_COMPLETE: 'media_complete',
  MEDIA_SEEK: 'media_seek',
  MEDIA_VOLUME: 'media_volume',
} as const;

export type AnalyticsEvent = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
export type AnalyticsAction = (typeof ANALYTICS_ACTIONS)[keyof typeof ANALYTICS_ACTIONS];

export const ANALYTICS_ELEMENTS = {
  HOME_LINK: 'home_link',
  NAV_LINK: 'nav_link',
  POST_OPEN: 'post_open',
  POST_BACK: 'post_back',
  SEARCH_OPEN: 'search_open',
  SEARCH_CLOSE: 'search_close',
  SEARCH_CLEAR: 'search_clear',
  SEARCH_INPUT: 'search_input',
  SEARCH_RESULT: 'search_result',
  SEARCH_FORM: 'search_form',
  MENU_OPEN: 'menu_open',
  MENU_CLOSE: 'menu_close',
  COLOR_MODE_TOGGLE: 'color_mode_toggle',
  DESIGN_SELECT: 'design_select',
  LANGUAGE_SELECT: 'language_select',
  GALLERY_OPEN: 'gallery_open',
  GALLERY_PREVIOUS: 'gallery_previous',
  GALLERY_NEXT: 'gallery_next',
  GALLERY_CLOSE: 'gallery_close',
  GALLERY_LOCATION: 'gallery_location',
  GALLERY_RETRY: 'gallery_retry',
  CONTACT_LINK: 'contact_link',
  PROJECT_LINK: 'project_link',
  RESUME_LINK: 'resume_link',
  DESIGN_ABOUT: 'design_about',
  DESIGN_PREVIEW: 'design_preview',
  FOOTER_LINK: 'footer_link',
  POST_PREVIOUS: 'post_previous',
  POST_NEXT: 'post_next',
  ARTICLE_LINK: 'article_link',
  ARTICLE_TOGGLE: 'article_toggle',
  ARTICLE_IMAGE: 'article_image',
  ARTICLE_IMAGE_CLOSE: 'article_image_close',
  ARTICLE_BUTTON: 'article_button',
  ARTICLE_COPY: 'article_copy',
  EMBED_OPEN: 'embed_open',
  MEDIA_CONTROL: 'media_control',
} as const;

export const ANALYTICS_SECTIONS = {
  HEADER: 'header',
  NAV_DOCK: 'nav_dock',
  MENU: 'menu',
  POST_LIST: 'post_list',
  SEARCH: 'search',
  ARTICLE: 'article',
  GALLERY: 'gallery',
  GALLERY_VIEWER: 'gallery_viewer',
  ABOUT_HERO: 'about_hero',
  ABOUT_PROJECTS: 'about_projects',
  ABOUT_CONTACT: 'about_contact',
  RESUME_CONTACT: 'resume_contact',
  RESUME_PROJECTS: 'resume_projects',
  DESIGN_PICKER: 'design_picker',
  DESIGN_STORY: 'design_story',
  FOOTER: 'footer',
} as const;

export const ANALYTICS_PAGES = {
  HOME: 'home',
  POST: 'post',
  ABOUT: 'about',
  RESUME: 'resume',
  GALLERY: 'gallery',
  PERSONAL: 'personal',
  DESIGNS: 'designs',
  ABOUT_DESIGN: 'about_design',
  UNKNOWN: 'unknown',
} as const;
