import type {Meta,StoryObj} from '@storybook/nextjs-vite';
import {useState} from 'react';
import {ParticipantCount} from '@/features/when-we-meet/ParticipantCount';
import {EmptyMeetings as EmptyMeetingsState} from '@/features/when-we-meet/EmptyMeetings';
import {within,userEvent} from 'storybook/test';
import WhenWeMeet from '@/features/when-we-meet/WhenWeMeet';
import {InvitationLanding} from '@/features/when-we-meet/InvitationLanding';
import {WeeklyAvailability} from '@/features/when-we-meet/WeeklyAvailability';
import {makeSlots} from '@/features/when-we-meet/domain.mjs';
import {MockAccountProvider,PERSON} from './mock-account';
import {state,type Room,type Response} from './mock-api';
import {MeetingRowsSkeleton,RoomSkeleton} from '@/features/when-we-meet/ServerSkeletons';
import ServerSectionBoundary from '@/features/when-we-meet/ServerSectionBoundary';
import SiteError from '@/components/site-error/SiteError';
import {saveDraft} from '@/features/when-we-meet/draft.mjs';
import {expect,waitFor} from 'storybook/test';
const id='22222222-2222-4222-8222-222222222222';
const room:Room={id,title:'Team coffee',owner_id:PERSON.id,role:'ADMIN',start_date:'2026-09-30',end_date:'2026-10-02',start_time:'00:00',end_time:'24:00',timezone:'Asia/Seoul',invite_token:'storybook-only'};
const slots=makeSlots({title:room.title,startDate:room.start_date,endDate:room.end_date,startTime:room.start_time,endTime:room.end_time,timezone:room.timezone}) as {id:string;utc:string;date:string;time:string}[];
const rows:Response[]=[{user_id:PERSON.id,display_name:'Alex Sample',slots:slots.slice(12,15).map(x=>x.id)},{user_id:'33333333-3333-4333-8333-333333333333',display_name:'Morgan Sample',slots:slots.slice(12,14).map(x=>x.id)}];
const meta={title:'When We Meet/Actual screens',component:WhenWeMeet,parameters:{nextjs:{appDirectory:true}}} satisfies Meta<typeof WhenWeMeet>;
export default meta;
type Story=StoryObj<typeof meta>;
function Frame({children,user=true,loading=false}:{children:React.ReactNode;user?:boolean;loading?:boolean}){return <MockAccountProvider value={{user:user?PERSON:null,loading}}><div className="light-wall light-page craft-chrome">{children}</div></MockAccountProvider>}
const list=<section className="wwm-card wwm-meetings" aria-label="Your meetings"><ul><li><a href="#storybook-room"><div className="wwm-meeting-title-row"><strong>Team coffee</strong><ParticipantCount count={15}/></div><span>2026.09.30 – 2026.10.02 · 00:00–24:00 · Asia/Seoul</span></a></li></ul></section>;
export const GuestHome:Story={render:()=> <Frame user={false}><WhenWeMeet meetingsSection={null}/></Frame>};
export const AccountLoading:Story={render:()=> <Frame user={false} loading><WhenWeMeet meetingsSection={null}/></Frame>};
export const EmptyMeetings:Story={render:()=> <Frame><WhenWeMeet meetingsSection={<section className="wwm-card wwm-meetings" aria-label="Your meetings"><EmptyMeetingsState/></section>}/></Frame>};
export const PopulatedMeetings:Story={render:()=> <Frame><WhenWeMeet meetingsSection={list}/></Frame>};
export const CreateDialog:Story={...EmptyMeetings,play:async({canvasElement})=>{await userEvent.click(within(canvasElement).getByRole('button',{name:'New meeting'}));}};
export const CreateValidationError:Story={...CreateDialog,play:async(ctx)=>{await CreateDialog.play?.(ctx);await userEvent.click(within(document.body).getByRole('button',{name:'Create room'}));}};
export const GuestCreateDialog:Story={...GuestHome,play:async({canvasElement})=>{await userEvent.click(within(canvasElement).getByRole('button',{name:'Create a room'}));}};
function StreamedAvailabilityDemo(){const [result]=useState(()=>{let resolve!:(v:{responses:Response[]})=>void;const promise=new Promise<{responses:Response[]}>(r=>{resolve=r});return {promise,resolve}});return <Frame><button type="button" onClick={()=>result.resolve({responses:rows})}>Resolve availability fixture</button><WhenWeMeet roomId={id} initialRoom={{room,responses:[],userId:PERSON.id}} responsesPromise={result.promise}/></Frame>}
export const RoomAvailabilityLoading:Story={render:()=> <StreamedAvailabilityDemo/>};
export const RoomAvailabilityStreamed:Story={...RoomAvailabilityLoading,play:async({canvasElement})=>{const c=within(canvasElement);await expect(c.getByRole('heading',{name:'Team coffee'})).toBeVisible();await expect(c.getByLabelText('Loading availability')).toBeVisible();await userEvent.click(c.getByRole('button',{name:'Resolve availability fixture'}));await waitFor(()=>expect(c.queryByLabelText('Loading availability')).not.toBeInTheDocument());await expect(c.getByRole('tab',{name:'Availability'})).toBeVisible();}};
export const RoomAvailability:Story={render:()=> <Frame><WhenWeMeet roomId={id} initialRoom={{room,responses:rows,userId:PERSON.id}}/></Frame>};
export const RoomEveryone:Story={...RoomAvailability,play:async({canvasElement})=>{await userEvent.click(within(canvasElement).getByRole('tab',{name:'Everyone'}));}};
export const RoomPeople:Story={...RoomAvailability,play:async({canvasElement})=>{const c=within(canvasElement);await userEvent.click(c.getByRole('tab',{name:'People'}));await waitFor(()=>expect(c.getByText('Taylor Sample')).toBeVisible());await expect(c.getByText('No availability yet')).toBeVisible();}};
export const RoomSettings:Story={...RoomAvailability,play:async({canvasElement})=>{await userEvent.click(within(canvasElement).getByRole('button',{name:'Settings'}));}};
export const RoomNoResponses:Story={render:()=> <Frame><WhenWeMeet roomId={id} initialRoom={{room,responses:[],userId:PERSON.id}}/></Frame>};
function Calendar({density,readOnly=false}:{density:'empty'|'single'|'double'|'many';readOnly?:boolean}){const [mine,setMine]=useState<string[]>(density==='empty'?[]:slots.slice(density==='many'?0:12,density==='many'?48:12+(density==='single'?1:2)).map(s=>s.id));return <div className="wwm wwm-room"><div className="wwm-shell"><section className="wwm-card wwm-availability"><WeeklyAvailability startDate={room.start_date} endDate={room.end_date} timezone={room.timezone} slots={slots} responses={density==='empty'?[]:density==='many'?Array.from({length:15},(_,i)=>({user_id:`person-${i}`,display_name:`Participant ${i+1}`,slots:slots.slice(12,18).map(s=>s.id)})):rows} currentUserId={PERSON.id} mine={mine} dirty={false} onToggle={slot=>setMine(old=>old.includes(slot)?old.filter(x=>x!==slot):[...old,slot])} readOnly={readOnly}/></section></div></div>}
export const EmptyCalendar:Story={render:()=> <Frame><Calendar density="empty"/></Frame>};
export const SingleHalfHour:Story={render:()=> <Frame><Calendar density="single"/></Frame>};
export const DoubleHalfHour:Story={render:()=> <Frame><Calendar density="double"/></Frame>};
export const FullDay:Story={render:()=> <Frame><Calendar density="many"/></Frame>};
export const ManyRespondents:Story={render:()=> <Frame><Calendar density="many" readOnly/></Frame>};
function Invite({signedIn=false,loading=false,busy=false,valid=true,error='',nameReady=false}:{signedIn?:boolean;loading?:boolean;busy?:boolean;valid?:boolean;error?:string;nameReady?:boolean}){const [name,setName]=useState('');return <Frame user={signedIn}><div className="wwm"><div className="wwm-shell"><InvitationLanding signedIn={signedIn} loading={loading} busy={busy} valid={valid} name={name} nameReady={nameReady} onName={setName} error={error} onSignIn={()=>{}} onJoin={()=>{}} onRetry={()=>{}}/></div></div></Frame>}
export const InvitationGuest:Story={render:()=> <Invite/>};
export const InvitationLoading:Story={render:()=> <Invite loading/>};
export const InvitationSignedIn:Story={render:()=> <Invite signedIn/>};
export const InvitationJoining:Story={render:()=> <Invite signedIn nameReady/>};
export const InvitationBusy:Story={render:()=> <Invite signedIn busy/>};
export const InvitationInvalid:Story={render:()=> <Invite valid={false}/>};
export const InvitationFailed:Story={render:()=> <Invite signedIn error="Unable to join meeting. Please try again."/>};
export const ListLoading:Story={render:()=> <Frame><WhenWeMeet meetingsSection={<MeetingRowsSkeleton/>}/></Frame>};
export const RoomLoading:Story={render:()=> <Frame><main className="wwm"><RoomSkeleton/></main></Frame>};
function BrokenSection():React.ReactNode{throw new Error('Synthetic section failure');}
export const ListLoadError:Story={render:()=> <Frame><WhenWeMeet meetingsSection={<ServerSectionBoundary><BrokenSection/></ServerSectionBoundary>}/></Frame>};
export const RoomLoadError:Story={render:()=> <Frame><main className="wwm"><ServerSectionBoundary><BrokenSection/></ServerSectionBoundary></main></Frame>};
export const RouteNotFound:Story={render:()=> <Frame><SiteError status="404"/></Frame>};
export const RouteServerError:Story={render:()=> <Frame><SiteError status="500" retry={<button onClick={()=>{}}>다시 시도</button>}/></Frame>};
const seeded=()=>saveDraft(sessionStorage,{form:{title:'Team coffee',startDate:'2026-09-30',endDate:'2026-10-02',startTime:'00:00',endTime:'24:00',timezone:'Asia/Seoul'},name:'Alex Sample'});
const submitCreate=async(ctx:Parameters<NonNullable<Story['play']>>[0])=>{await CreateDialog.play?.(ctx);await userEvent.click(within(document.body).getByRole('button',{name:'Create room'}));};
export const RestoredDraft:Story={...CreateDialog,beforeEach:seeded};
export const CreateSubmitting:Story={...EmptyMeetings,beforeEach:()=>{seeded();state.create='pending';},play:submitCreate};
export const CreateFailure:Story={...EmptyMeetings,beforeEach:()=>{seeded();state.create='failure';},play:submitCreate};
export const CreateSuccess:Story={...EmptyMeetings,beforeEach:()=>{seeded();state.create='success';},play:submitCreate};
export const LoginRequired:Story={...GuestHome,beforeEach:seeded,play:async(ctx)=>{await GuestCreateDialog.play?.(ctx);await userEvent.click(within(document.body).getByRole('button',{name:'Create room'}));await waitFor(()=>expect(within(document.body).getByText('Sign in with Google to create a room')).toBeVisible());}};
const editCell=async({canvasElement}:Parameters<NonNullable<Story['play']>>[0])=>{const cell=canvasElement.querySelector<HTMLButtonElement>('.wwm-week-edit');if(!cell)throw Error('Edit cell missing');await userEvent.click(cell);};
export const Saving:Story={...RoomAvailability,beforeEach:()=>{state.save='pending';},play:async(ctx)=>{await editCell(ctx);await waitFor(()=>expect(within(ctx.canvasElement).getByText(/Saving/)).toBeVisible());}};
export const SaveFailed:Story={...RoomAvailability,beforeEach:()=>{state.save='failure';},play:async(ctx)=>{await editCell(ctx);await waitFor(()=>expect(within(ctx.canvasElement).getByText(/Not saved/)).toBeVisible());}};
export const SaveRetryRecovered:Story={...SaveFailed,play:async(ctx)=>{await SaveFailed.play?.(ctx);state.save='success';await userEvent.click(within(ctx.canvasElement).getByRole('button',{name:'Retry'}));await waitFor(()=>expect(within(ctx.canvasElement).getByText(/All changes saved/)).toBeVisible());}};
export const LiveConnected:Story={...RoomAvailability,beforeEach:()=>{state.connected=true;state.responses=rows;},play:async({canvasElement})=>{await waitFor(()=>expect(within(canvasElement).getByText(/Live updates/)).toBeVisible());}};
export const ConnectionUnavailable:Story={...RoomAvailability};
export const SessionExpiredOnSave:Story={...SaveFailed,beforeEach:()=>{state.save='failure';state.message='Session expired. Sign in again.';}};
export const AccessDeniedOnSave:Story={...SaveFailed,beforeEach:()=>{state.save='failure';state.message='You do not have permission to edit this meeting.';}};
export const InvitationMissingToken:Story={render:()=> <Frame><WhenWeMeet roomId={id}/></Frame>};
export const AlreadyJoined:Story={...RoomAvailability,parameters:{docs:{description:{story:'An existing member opens the room: the server supplies initialRoom, bypassing the invitation landing.'}}}};
export const NameRequiredToJoin:Story={render:()=> <Invite signedIn/>};
export const CalendarMobile:Story={...RoomAvailability,globals:{viewport:{value:'mobile',isRotated:false}}};
export const CalendarDark:Story={...RoomAvailability,globals:{theme:'dark'}};

