import test from 'node:test';
import assert from 'node:assert/strict';
import {saveDraft,readDraft,markCreateReturn,completeCreateReturn,consumeCreateReturn} from '../src/features/when-we-meet/draft.mjs';
import {creationErrors} from '../src/features/when-we-meet/creation-validation.mjs';
const form={title:'Coffee',startDate:'2026-10-10',endDate:'2026-10-12',startTime:'09:00',endTime:'17:30',timezone:'Asia/Seoul'};
const clock=new Date('2026-10-07T00:00:00Z');
function storage(){const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)}}
for(const scheduleMode of ['time','date'])test(`v2 ${scheduleMode} draft preserves hidden times and OAuth completion`,()=>{const s=storage();saveDraft(s,{form:{...form,scheduleMode},name:' Kim '},100);assert.equal(JSON.parse(s.getItem('wwm:create-draft')).version,2);assert.deepEqual(readDraft(s,101),{form:{...form,scheduleMode},name:' Kim '});markCreateReturn(s,'/craft/when-we-meet',100);assert.equal(completeCreateReturn(s,'/craft/when-we-meet',101),true);assert.equal(consumeCreateReturn(s,'/craft/when-we-meet',102),true);assert.equal(consumeCreateReturn(s,'/craft/when-we-meet',103),false)});
test('v1 migrates to time; unknown v2 mode rejected; expiry unchanged',()=>{const s=storage();s.setItem('wwm:create-draft',JSON.stringify({version:1,savedAt:100,form,name:'Kim'}));assert.equal(readDraft(s,101).form.scheduleMode,'time');assert.equal(readDraft(s,100+24*60*60*1000+1),null);s.setItem('wwm:create-draft',JSON.stringify({version:2,savedAt:100,form:{...form,scheduleMode:'weekly'},name:'Kim'}));assert.equal(readDraft(s,101),null)});
test('time validates hidden malformed times, date ignores times, unknown mode rejected',()=>{const values={...form,name:'Kim',startTime:'bad'};assert.ok(creationErrors({...values,scheduleMode:'time'},clock).times);assert.deepEqual(creationErrors({...values,scheduleMode:'date'},clock),{});assert.ok(creationErrors({...values,scheduleMode:'weekly'},clock).scheduleMode);assert.ok(creationErrors({...values,scheduleMode:null},clock).scheduleMode)});
test('date retains common timezone/past/range/title/name validation',()=>{for(const patch of [{timezone:'invalid'},{startDate:'2026-10-01'},{endDate:'2026-11-10'},{title:' '},{name:' '}])assert.ok(Object.keys(creationErrors({...form,name:'Kim',scheduleMode:'date',...patch},clock)).length)});
test('mode-specific dispatch sends exact payload and retains time endpoint',async()=>{const {submitCreation}=await import('../src/features/when-we-meet/date-creation.mjs');const calls=[];const api={createRoom:async(...args)=>{calls.push(['time',...args]);return {id:'time'}},createDateRoom:async(...args)=>{calls.push(['date',...args]);return {id:'date'}}};assert.deepEqual(await submitCreation({...form,scheduleMode:'date'},' Kim ',api),{id:'date'});assert.deepEqual(calls[0],['date',{title:form.title,startDate:form.startDate,endDate:form.endDate,timezone:form.timezone,scheduleMode:'date',name:'Kim'}]);await submitCreation({...form,scheduleMode:'time'},' Kim ',api);assert.deepEqual(calls[1],['time',form,'Kim']);await assert.rejects(()=>submitCreation({...form,scheduleMode:'bad'},'Kim',api));assert.equal(calls.length,2)});
