import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import * as normalize from '../src/features/when-we-meet/normalize.mjs';
import {meetingSummary,createMeetingCopy} from '../src/features/when-we-meet/meeting-copy.mjs';
const time={id:'time',owner_id:'owner',title:'Time',start_date:'2026-12-31',end_date:'2027-01-01',start_time:'09:00:00',end_time:'18:00:00',timezone:'Pacific/Honolulu',created_at:'2026-10-07'};
const date={...time,id:'date',schedule_mode:'date',start_time:null,end_time:null};
function load(path,imports){const module={exports:{}};const code=ts.transpileModule(fs.readFileSync(new URL(path,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;vm.runInNewContext(`(function(require,module,exports){${code}})`,{})(name=>{if(name in imports)return imports[name];throw Error(name)},module,module.exports);return module.exports;}
function owned(){return load('../src/lib/supabase/server.ts',{'next/headers':{},'@supabase/ssr':{},'@/lib/request-origin.mjs':{},'@/features/when-we-meet/room-permissions.mjs':{},'@/features/when-we-meet/normalize.mjs':normalize}).ownedCraftMeetings;}
function context(results=[{data:[time,date]}],rpcError=false){const queries=[],rpcs=[];return {user:{id:'owner'},queries,rpcs,client:{from(table){const q={table,filters:[]};queries.push(q);return {select(columns){q.columns=columns;return this},eq(key,value){q.filters.push([key,value]);return this},async order(key,options){q.order=[key,options];return results.shift()}}},async rpc(name,args){rpcs.push([name,args]);return rpcError?{error:{code:'XX000'}}:{data:name==='wwm_participant_counts'?[{room_id:'date',participant_count:3},{room_id:'time',participant_count:2}]:[{status:'confirmed'}]}}}};}
test('date metadata preserves null clocks and explicit discriminator',()=>{const m=normalize.normalizeMeeting(date);assert.equal(m.scheduleMode,'date');assert.equal(m.startTime,null);assert.equal(m.endTime,null);assert.equal(m.startDate,'2026-12-31');assert.equal(m.endDate,'2027-01-01');assert.equal('inviteToken' in m,false)});
test('absent and explicit time mode retain timed metadata',()=>{for(const row of [time,{...time,schedule_mode:'time'}]){const m=normalize.normalizeMeeting(row);assert.equal(m.scheduleMode,'time');assert.equal(m.startTime,'09:00');assert.equal(m.endTime,'18:00')}});
for(const [name,row] of [['unknown mode',{...time,schedule_mode:'foo'}],['null mode',{...time,schedule_mode:null}],['date with clocks',{...date,start_time:'09:00'}],['time with null clocks',{...time,start_time:null}],['absent mode with null clocks',{...date,schedule_mode:undefined}]])test(`rejects ${name}`,()=>assert.throws(()=>normalize.normalizeMeeting(row)));
test('date summaries use localized All day without clock sentinels or instant conversion',()=>{const m=normalize.normalizeMeeting(date);assert.equal(meetingSummary(m),'2026.12.31 – 2027.01.01 · All day · Pacific/Honolulu');assert.equal(createMeetingCopy('ko').meetingSummary(m),`2026.12.31 – 2027.01.01 · ${createMeetingCopy('ko').t('common.allDay')} · Pacific/Honolulu`);assert.doesNotMatch(meetingSummary(m),/null|undefined|00:00|24:00/)});
test('timed summaries including legacy full-day remain unchanged',()=>{assert.equal(meetingSummary(normalize.normalizeMeeting(time)),'2026.12.31 – 2027.01.01 · 09:00–18:00 · Pacific/Honolulu');assert.match(meetingSummary({...normalize.normalizeMeeting(time),startTime:'00:00',endTime:'24:00'}),/All day/)});
test('owned mixed read selects mode, filters current owner and preserves RPC metadata',async()=>{const c=context();const result=await owned()(c);assert.deepEqual(result.meetings.map(m=>m.scheduleMode),['time','date']);assert.equal(result.meetings[1].participantCount,3);assert.equal(result.meetings[0].confirmationStatus,'confirmed');assert.equal(result.userId,'owner');assert.match(c.queries[0].columns,/schedule_mode/);assert.deepEqual(c.queries[0].filters,[['owner_id','owner']]);assert.equal(c.rpcs.length,3)});
test('42703 alone retries legacy columns with owner filter',async()=>{const c=context([{error:{code:'42703'}},{data:[time]}]);const result=await owned()(c);assert.equal(result.meetings[0].scheduleMode,'time');assert.equal(c.queries.length,2);assert.doesNotMatch(c.queries[1].columns,/schedule_mode/);for(const q of c.queries)assert.deepEqual(q.filters,[['owner_id','owner']])});
test('other DB errors do not retry or call RPC',async()=>{const c=context([{error:{code:'XX000'}}]);await assert.rejects(()=>owned()(c),/Could not load/);assert.equal(c.queries.length,1);assert.equal(c.rpcs.length,0)});
test('fallback errors are surfaced',async()=>{const c=context([{error:{code:'42703'}},{error:{code:'42501'}}]);await assert.rejects(()=>owned()(c),/Could not load/);assert.equal(c.rpcs.length,0)});
test('failed RPC metadata remains unavailable rather than fabricated',async()=>{const result=await owned()(context(undefined,true));for(const m of result.meetings){assert.equal(m.participantCount,null);assert.equal(m.confirmationStatus,null)}});
test('signed-out list performs no private reads',async()=>{const c=context();c.user=null;const result=await owned()(c);assert.equal(result.meetings.length,0);assert.equal(result.userId,null);assert.equal(c.queries.length,0)});
test('generic GET delegates to the mode-aware owned read',async()=>{const c=context();const route=load('../src/app/api/craft/when-we-meet/route.ts',{'@/lib/supabase/server':{currentSupabaseUser:async()=>c,ownedCraftMeetings:owned()},'./http':{ok:value=>value,failed:()=>{throw Error('failed')},unauthorized:()=>null},'@/features/when-we-meet/domain.mjs':{},'@/features/when-we-meet/creation-validation.mjs':{},'@/features/when-we-meet/normalize.mjs':normalize});const result=await route.GET();assert.equal(result.meetings[1].scheduleMode,'date');assert.equal(result.meetings[1].startTime,null)});
