import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=()=>readFileSync(new URL('../src/features/when-we-meet/ConfirmationPanel.tsx',import.meta.url),'utf8');
test('confirmation UI requires explicit review and send callbacks, without fetch',()=>{const s=source();assert.match(s,/onConfirm:/);assert.match(s,/onConnectCalendar:/);assert.match(s,/t\('confirm\.send'\)/);assert.doesNotMatch(s,/\bfetch\s*\(/);});
test('recipient exclusions and missing addresses are reviewed',()=>{const s=source();assert.match(s,/excludedIds/);assert.match(s,/t\('confirm\.missingEmail'\)/);assert.match(s,/t\('confirm\.status\.notResponded'\)/);assert.match(s,/t\('confirm\.warnings\.unavailable'/);});
const weekly=()=>readFileSync(new URL('../src/features/when-we-meet/WeeklyAvailability.tsx',import.meta.url),'utf8');
const panelCss=()=>readFileSync(new URL('../src/features/when-we-meet/confirmation-panel.css',import.meta.url),'utf8');
test('the confirm calendar is the compact Everyone calendar, not a separate count grid',()=>{const s=source();assert.match(s,/<WeeklyAvailability [^>]*selection=\{selection\}\/>/);assert.doesNotMatch(s,/wwm-confirm-grid|wwm-confirm-cell|available:number/);assert.doesNotMatch(panelCss(),/wwm-confirm-grid|wwm-confirm-cell/);
 const w=weekly();assert.match(w,/compact=Boolean\(selection\)\|\|/);assert.match(w,/\{!selection&&readOnly&&<ToggleGroup [^>]*className="wwm-segmented"/);assert.match(w,/readOnly=everyoneView\|\|Boolean\(selection\)/);});
test('selection cells name date, time and N of M members; rails are visual only while selecting',()=>{const w=weekly();
 assert.match(w,/if\(selection\)return `\$\{t\('grid\.cellCount',\{when,count,total:selection\.memberCount\}\)\}/);
 assert.match(w,/selecting\?ANALYTICS_ELEMENTS\.CONFIRM_CELL/);assert.match(w,/<div className="wwm-calendar-events" aria-hidden="true">/);assert.match(w,/tabIndex=\{-1\}/);
 assert.match(w,/gesture\.current\.down\('touch'/);assert.match(w,/if\(event\.key==='Enter'\|\|event\.key===' '\)\{event\.preventDefault\(\);activate\(slot\);return\}/);assert.match(w,/if\(selecting\)tap\(slot\)/);});
test('calendar and fields edit one selection and the proposal carries the selected slot ids',()=>{const s=source();assert.match(s,/const nextRange=fieldsRange\(slots,next\)[^]*setRange\(nextRange\)/);assert.match(s,/const fields=rangeFields\(slots,next\)/);assert.match(s,/startId:range\.startId,endId:range\.endId/);assert.match(s,/onChange:busy\?undefined:selectRange/);assert.match(s,/rangeLabel:t\('common\.confirmed'\)/);});
