import test from 'node:test';
import assert from 'node:assert/strict';
const m=await import('../src/features/when-we-meet/date-save.mjs').catch(()=>({}));
const id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',uid='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';
const room={id,owner_id:uid,title:'D',schedule_mode:'date',start_date:'2026-10-06',end_date:'2026-10-08',start_time:null,end_time:null,timezone:'UTC'};
const row={user_id:uid,display_name:'Remote',available_dates:['2026-10-07'],slots:[],updated_at:'2026-10-06T00:00:00.123456Z'};
function fake(options={}){const calls=[];let reads=0,writes=0;const client={from(table){const filters={};const q={select(columns){calls.push({table,columns});return q},eq(key,value){filters[key]=value;return q},limit(){return Promise.resolve({data:[],error:options.probeError})},single(){if(table==='wwm_rooms'){reads++;return Promise.resolve({data:options.denied?null:{...room,...options.roomPatch,...(reads>1?options.shrink:{})},error:options.readError})}return Promise.resolve({data:{...row,...(writes?options.remote:{})},error:null})},then(resolve,reject){return Promise.resolve({data:[row],error:null}).then(resolve,reject)}};return q},async rpc(name,args){calls.push({name,args});if(name==='wwm_save_dates'){writes++;if(options.conflicts===Infinity||writes<=options.conflicts)return {error:{code:'40001'}};return {data:[{updated_at:'2026-10-06T00:00:00.654321Z'}],error:options.rpcError}}if(name==='wwm_create_date_room')return {data:{id,invite_token:uid},error:options.rpcError};return {data:[{start_date:args.p_start_date,end_date:args.p_end_date,timezone:args.p_timezone,removed_dates:2}],error:options.rpcError}}};return {context:{client,user:{id:options.nonowner?id:uid,app_metadata:{provider:options.provider??'google'}}},calls,get reads(){return reads},get writes(){return writes}}}
const save={action:'saveDates',name:'Base',availableDates:['2026-10-06'],base:{name:'Base',availableDates:[]}};
async function service(f){assert.equal(typeof m.createDateService,'function');return m.createDateService(f.context,{clock:new Date('2026-10-06T12:00:00Z')});}
const status=n=>e=>e.status===n;
test('load explicitly date RLS member room without emails',async()=>{const f=fake(),s=await service(f);const r=await s.load(id);assert.equal(r.room.role,'ADMIN');assert.equal(r.responses[0].updatedAt,row.updated_at);assert.equal('email' in r.responses[0],false)});
test('save rebases date delta and unchanged name preserves remote',async()=>{const f=fake(),s=await service(f),r=await s.save(id,save);assert.deepEqual(r.value,{name:'Remote',availableDates:['2026-10-06','2026-10-07'],version:'2026-10-06T00:00:00.654321Z'});assert.equal(f.calls.find(c=>c.name==='wwm_save_dates').args.p_expected_updated_at,row.updated_at)});
test('name-only edit preserves remote dates',async()=>{const f=fake(),s=await service(f);assert.equal((await s.save(id,{...save,name:'New',availableDates:[]})).value.name,'New');assert.deepEqual(f.calls.find(c=>c.name==='wwm_save_dates').args.p_available_dates,['2026-10-07'])});
test('no change retains remote',async()=>{const s=await service(fake());assert.deepEqual((await s.save(id,{...save,availableDates:[]})).value.availableDates,['2026-10-07'])});
test('40001 rereads room and response and preserves newer name/date',async()=>{const f=fake({conflicts:1,remote:{display_name:'Latest',available_dates:['2026-10-08'],updated_at:'2026-10-06T00:00:00.222222Z'}}),s=await service(f);assert.deepEqual((await s.save(id,save)).value.availableDates,['2026-10-06','2026-10-08']);assert.equal(f.reads,2);assert.equal(f.writes,2);assert.equal(f.calls.filter(c=>c.name==='wwm_save_dates')[1].args.p_expected_updated_at,'2026-10-06T00:00:00.222222Z')});
test('retry exhausted at four writes',async()=>{const f=fake({conflicts:Infinity}),s=await service(f);await assert.rejects(s.save(id,save),status(409));assert.equal(f.writes,4);assert.equal(f.reads,4)});
test('shrink race rejects stale dates before second write',async()=>{const f=fake({conflicts:1,shrink:{start_date:'2026-10-07'}}),s=await service(f);await assert.rejects(s.save(id,save),status(400));assert.equal(f.writes,1)});
test('missing baseline conflict',async()=>{const s=await service(fake());await assert.rejects(s.save(id,{...save,base:undefined}),status(409))});
for(const value of [['2026-10-09'],['infinity'],[null]])test(`invalid dates ${JSON.stringify(value)}`,async()=>{const s=await service(fake());await assert.rejects(s.save(id,{...save,availableDates:value}),status(400))});
test('duplicate dates normalized at save',async()=>{const s=await service(fake());assert.deepEqual((await s.save(id,{...save,availableDates:['2026-10-06','2026-10-06']})).value.availableDates,['2026-10-06','2026-10-07'])});
test('nonmember denied without write',async()=>{const f=fake({denied:true}),s=await service(f);await assert.rejects(s.save(id,save),status(403));assert.equal(f.writes,0)});
test('nonowner schedule forbidden',async()=>{const s=await service(fake({nonowner:true}));await assert.rejects(s.schedule(id,{startDate:'2026-10-06',endDate:'2026-10-08',timezone:'UTC'}),status(403))});
test('historical current start retained',async()=>{const f=fake(),s=await service(f);const r=await s.schedule(id,{startDate:'2026-10-06',endDate:'2026-10-07',timezone:'UTC'});assert.equal(r.removedDates,2)});
test('creation uses exact RPC parameters and fresh dates',async()=>{const f=fake(),s=await service(f);assert.deepEqual(await s.create({scheduleMode:'date',title:'D',name:'N',startDate:'2026-10-06',endDate:'2026-10-08',timezone:'UTC'}),{id,inviteToken:uid});assert.deepEqual(f.calls.find(c=>c.name==='wwm_create_date_room').args,{p_title:'D',p_name:'N',p_start_date:'2026-10-06',p_end_date:'2026-10-08',p_timezone:'UTC'})});
for(const patch of [{startTime:'00:00'},{scheduleMode:'time'},{startDate:'2026-10-05'},{timezone:'bad/zone'},{title:''},{name:''}])test(`invalid creation ${JSON.stringify(patch)}`,async()=>{const s=await service(fake());await assert.rejects(s.create({scheduleMode:'date',title:'D',name:'N',startDate:'2026-10-06',endDate:'2026-10-08',timezone:'UTC',...patch}),status(400))});
for(const code of ['42703','42883','PGRST202','PGRST204'])test(`missing migration ${code}`,async()=>{const s=await service(fake({rpcError:{code,message:'secret'}}));await assert.rejects(s.save(id,save),e=>e.status===503&&!e.message.includes('secret'))});
for(const [code,n] of [['42501',403],['22023',400],['P0002',403],['XX000',500]])test(`safe SQLSTATE ${code}`,async()=>{const s=await service(fake({rpcError:{code,message:'secret'}}));await assert.rejects(s.save(id,save),e=>e.status===n&&!e.message.includes('secret'))});
test('capability checks actual schema using RLS limit zero',async()=>{const f=fake(),s=await service(f);assert.deepEqual(await s.capability(),{supported:true});assert.equal(f.calls[0].columns,'schedule_mode')});
test('capability missing schema fails closed',async()=>{const s=await service(fake({probeError:{code:'42703'}}));await assert.rejects(s.capability(),status(503))});
for(const provider of ['email',null])test(`google auth guard ${provider}`,async()=>{assert.equal(typeof m.createDateService,'function');assert.throws(()=>m.createDateService(provider===null?{client:{},user:null}:fake({provider}).context),status(401))});
// Exercise the same HTTP adapter called by both route modules; auth is injected, not real cookies.
const {createJiti}=await import('jiti');
const jiti=createJiti(import.meta.url,{alias:{'@':new URL('../src/',import.meta.url).pathname},moduleCache:false});
const http=await jiti.import('../src/app/api/craft/when-we-meet/http.ts');
async function handle(request,context=fake().context,roomId=id){assert.equal(typeof m.handleDateRequest,'function');return m.handleDateRequest(request,roomId,{currentUser:async()=>context,...http});}
const req=(value=save,headers={})=>new Request('http://localhost:3002/api/craft/when-we-meet/'+id+'/dates',{method:'POST',headers:{host:'localhost:3002',origin:'http://localhost:3002','content-type':'application/json',...headers},body:typeof value==='string'?value:JSON.stringify(value)});
test('HTTP saves through actual service and RLS transport',async()=>{const r=await handle(req());assert.equal(r.status,200);assert.equal((await r.json()).value.version,'2026-10-06T00:00:00.654321Z');assert.equal(r.headers.get('cache-control'),'private, no-store')});
for(const [label,request,n] of [['origin',req(save,{origin:'https://foreign.test'}),403],['content type',req(save,{'content-type':'text/plain'}),400],['oversized',req('x'.repeat(8193)),400],['malformed',req('{'),400],['action',req({...save,action:'save'}),400]])test(`HTTP rejects ${label}`,async()=>{assert.equal((await handle(request)).status,n)});
test('HTTP missing identity unauthorized',async()=>{assert.equal((await handle(req(),{client:{},user:null})).status,401)});
test('HTTP rejects malformed UUID',async()=>{assert.equal((await handle(req(),fake().context,'not-uuid')).status,400)});
test('HTTP GET loads via same service',async()=>{const r=await handle(new Request('http://localhost:3002'));assert.equal(r.status,200);assert.equal((await r.json()).room.scheduleMode,'date')});
test('actual route modules reject foreign origin before auth',async()=>{for(const file of ['../src/app/api/craft/when-we-meet/dates/route.ts','../src/app/api/craft/when-we-meet/[roomId]/dates/route.ts']){const route=await jiti.import(file);const result=await route.POST(req(save,{origin:'https://foreign.test'}),{params:Promise.resolve({roomId:id})});assert.equal(result.status,403)}});
test('typed client uses date paths, JSON actions and same-origin credentials',async()=>{const api=await jiti.import('../src/features/when-we-meet/date-api.ts');const prior=globalThis.fetch,calls=[];globalThis.fetch=async(url,init)=>{calls.push({url,init});return Response.json({supported:true})};try{await api.checkDateModeCapability();await api.createDateRoom({scheduleMode:'date',title:'D',name:'N',startDate:'2026-10-06',endDate:'2026-10-08',timezone:'UTC'});await api.loadDateRoom(id);await api.saveDateResponse(id,'N',['2026-10-06'],{name:'N',availableDates:[]});await api.updateDateRoomSchedule(id,{startDate:'2026-10-06',endDate:'2026-10-07',timezone:'UTC'});assert.equal(calls.length,5);assert.equal(calls[0].url,'/api/craft/when-we-meet/dates');assert.equal(calls[2].url,`/api/craft/when-we-meet/${id}/dates`);assert.equal(JSON.parse(calls[3].init.body).action,'saveDates');assert.equal(JSON.parse(calls[4].init.body).action,'scheduleDates');for(const {init} of calls)assert.equal(init.credentials,'same-origin')}finally{globalThis.fetch=prior}});
test('HTTP byte limit rejects multibyte payload below character limit',async()=>{const request=req({...save,padding:'한'.repeat(3000)});assert.equal((await handle(request)).status,400)});
test('anonymous Google identity rejected',()=>{const context=fake().context;context.user.is_anonymous=true;assert.throws(()=>m.createDateService(context),status(401))});
test('historical schedule exception only retains current start',async()=>{const s=m.createDateService(fake().context,{clock:new Date('2026-10-20T00:00:00Z')});assert.equal((await s.schedule(id,{startDate:'2026-10-06',endDate:'2026-10-08',timezone:'UTC'})).removedDates,2);await assert.rejects(s.schedule(id,{startDate:'2026-10-07',endDate:'2026-10-08',timezone:'UTC'}),status(400))});
for(const [mode,n] of [['time',400],[undefined,503],['unknown',500]])test(`date endpoint mode ${String(mode)} fails closed`,async()=>{const f=fake({roomPatch:{schedule_mode:mode}}),s=await service(f);await assert.rejects(s.save(id,save),status(n));assert.equal(f.writes,0)});
test('foreign own-response identity rejected without CAS',async()=>{const f=fake({nonowner:true}),s=await service(f);await assert.rejects(s.save(id,save),status(403));assert.equal(f.writes,0)});
function streamedRequest(chunkSize,totalChunks,options={}){
 let produced=0,cancelled=false;
 const stream=new ReadableStream({pull(controller){if(produced===totalChunks){controller.close();return}produced++;controller.enqueue(new Uint8Array(chunkSize).fill(120))},cancel(){cancelled=true;return options.cancelNever?new Promise(()=>{}):undefined}});
 const request=new Request('http://localhost:3002/api/craft/when-we-meet/'+id+'/dates',{method:'POST',headers:{host:'localhost:3002',origin:'http://localhost:3002','content-type':'application/json',...options.headers},body:stream,duplex:'half'});
 return {request,stream,get produced(){return produced},get cancelled(){return cancelled}};
}
async function unauthenticated(request,extra={}){let authCalls=0;const result=await m.handleDateRequest(request,id,{...http,currentUser:async()=>{authCalls++;return {client:{},user:null}},...extra});return {result,authCalls};}
test('HTTP stops unauthenticated unknown-length 16 MiB stream at first oversized chunk',async()=>{
 const source=streamedRequest(65536,256),{result,authCalls}=await unauthenticated(source.request);
 assert.equal(result.status,400);assert.equal(authCalls,0);
 assert.ok(source.produced<256,`produced all ${source.produced} chunks (16 MiB)`);
 assert.ok(source.produced<=2,`produced ${source.produced} chunks`);assert.equal(source.cancelled,true);assert.equal(source.stream.locked,false);
});
test('HTTP bounds small-chunk consumption and does not await stalled cancellation',async()=>{
 const source=streamedRequest(1024,256,{cancelNever:true});
 const {result,authCalls}=await Promise.race([unauthenticated(source.request),new Promise((_,reject)=>{const timer=setTimeout(()=>reject(new Error('body cancellation hung')),1000);timer.unref()})]);
 assert.equal(result.status,400);assert.equal(authCalls,0);assert.ok(source.produced<=10,`produced ${source.produced} KiB`);assert.equal(source.cancelled,true);assert.equal(source.stream.locked,false);
});
test('HTTP declared large length rejects before reading beyond initial queue',async()=>{const source=streamedRequest(1024,256,{headers:{'content-length':'16777216'}});const {result,authCalls}=await unauthenticated(source.request);assert.equal(result.status,400);assert.equal(authCalls,0);assert.ok(source.produced<=1);assert.equal(source.cancelled,true)});
test('HTTP limited buffer parses once without clone or injected body reread',async()=>{
 const request=req();request.clone=()=>{throw new Error('clone forbidden')};request.json=()=>{throw new Error('json reread forbidden')};request.text=()=>{throw new Error('text reread forbidden')};
 const original=JSON.parse;let parses=0;JSON.parse=(...args)=>{parses++;return original(...args)};
 try{const result=await m.handleDateRequest(request,id,{...http,body:()=>{throw new Error('shared body reread forbidden')},currentUser:async()=>fake().context});assert.equal(result.status,200);assert.equal(parses,1)}finally{JSON.parse=original}
});
for(const text of ['', 'null','[]','"text"','42','{'])test(`HTTP rejects nonobject JSON ${JSON.stringify(text)} before auth`,async()=>{const {result,authCalls}=await unauthenticated(req(text));assert.equal(result.status,400);assert.equal(authCalls,0)});
for(const bytes of [8191,8192,8193])test(`HTTP UTF8 JSON byte boundary ${bytes}`,async()=>{const base=JSON.stringify({...save,padding:'한🙂'}),text=base.slice(0,-2)+'x'.repeat(bytes-Buffer.byteLength(base))+base.slice(-2);assert.equal(Buffer.byteLength(text),bytes);assert.equal((await handle(req(text))).status,bytes<=8192?200:400)});
for(const length of ['garbage','-1','0'])test(`HTTP actual byte limit ignores untrusted length ${length}`,async()=>{const source=streamedRequest(1024,256,{headers:{'content-length':length}});const {result,authCalls}=await unauthenticated(source.request);assert.equal(result.status,400);assert.equal(authCalls,0);assert.ok(source.produced<=10);assert.equal(source.cancelled,true)});
test('HTTP abort cancels stalled body and releases reader',async()=>{
 const controller=new AbortController();let cancelled=false;const stream=new ReadableStream({cancel(){cancelled=true}});
 const request=new Request('http://localhost:3002',{method:'POST',headers:{host:'localhost:3002',origin:'http://localhost:3002','content-type':'application/json'},body:stream,duplex:'half',signal:controller.signal});
 const pending=unauthenticated(request);controller.abort();const {result,authCalls}=await pending;assert.equal(result.status,400);assert.equal(authCalls,0);assert.equal(cancelled,true);assert.equal(stream.locked,false);
});
export {fake,id,uid,save};
