import test from 'node:test';
import assert from 'node:assert/strict';
import {createJiti} from 'jiti';
const jiti=createJiti(import.meta.url,{alias:{'server-only':new URL('../node_modules/next/dist/compiled/server-only/empty.js',import.meta.url).pathname,'@':new URL('../src/',import.meta.url).pathname},moduleCache:false});
const id='11111111-1111-4111-8111-111111111111';
test('typed date client preserves reconnect flag from actual service before reservation',async()=>{
 const api=await jiti.import('../src/features/when-we-meet/date-confirmation-api.ts');
 const {handleDateConfirmationRequest}=await import('../src/features/when-we-meet/date-confirmation-service.mjs');
 const old=globalThis.fetch,calls=[];
 const deps={sameOrigin:()=>true,currentUser:async()=>({user:{id,app_metadata:{providers:['google']}}}),loadRoom:async()=>({id,role:'ADMIN',scheduleMode:'date',startTime:null,endTime:null,startDate:'2099-01-01',endDate:'2099-01-04',timezone:'UTC'}),loadOwner:async()=>null,attendees:async()=>[{userId:id,email:'Synthetic@example.test'}],token:async()=>{calls.push('token');throw Object.assign(new Error('synthetic-secret-token'),{reconnect:true});},reserve:async()=>{calls.push('reserve');}};
 globalThis.fetch=async(url,init)=>{const response=await handleDateConfirmationRequest(new Request('https://example.test'+url,init),id,'initial',deps);assert.equal((await response.clone().json()).code,'calendar_reconnect');return response;};
 try{await assert.rejects(()=>api.confirmDateMeetingRoute(id,{date:'2099-01-01',title:'Meeting',revision:1,recipients:[id]}),error=>{assert.ok(error instanceof api.ApiError);assert.equal(error.status,409);assert.equal(error.reconnect,true);assert.ok(!error.message.includes('synthetic-secret-token'));return true;});assert.deepEqual(calls,['token']);}finally{globalThis.fetch=old;}
});
test('actual date route modules reject foreign origin before auth',async()=>{for(const suffix of ['','/update','/resend']){const route=await jiti.import(`../src/app/api/craft/when-we-meet/[roomId]/dates/confirmation${suffix}/route.ts`);const r=await route.POST(new Request('http://localhost:3002/api',{method:'POST',headers:{host:'localhost:3002',origin:'https://foreign.test','content-type':'application/json'},body:'{"action":"send"}'}),{params:Promise.resolve({roomId:id})});assert.equal(r.status,403);}});
test('typed client uses parallel paths explicit actions and same-origin transport',async()=>{const api=await jiti.import('../src/features/when-we-meet/date-confirmation-api.ts'),old=globalThis.fetch,calls=[];globalThis.fetch=async(url,init)=>{calls.push({url,init});return Response.json({status:'confirmed'});};try{await api.getDateConfirmation(id);await api.confirmDateMeetingRoute(id,{date:'2099-01-01',title:'T',revision:1,recipients:[id]});await api.updateDateMeetingRoute(id,{date:'2099-01-02',title:'T',revision:2,recipients:[id]});await api.reconcileDateMeetingRoute(id);await api.reconcileDateMeetingRoute(id,'update');await api.resendDateMeetingRoute(id);assert.equal(calls.length,6);assert.equal(calls[0].url,`/api/craft/when-we-meet/${id}/dates/confirmation`);assert.ok(calls[2].url.endsWith('/update'));assert.ok(calls[5].url.endsWith('/resend'));assert.equal(JSON.parse(calls[3].init.body).action,'reconcile');for(const x of calls)assert.equal(x.init.credentials,'same-origin');}finally{globalThis.fetch=old;}});
test('runtime member status rejects malformed civil bounds and strips unknown PII',async()=>{const {createDateConfirmationRuntime}=await jiti.import('../src/features/when-we-meet/date-confirmation-runtime.ts');const runtime=createDateConfirmationRuntime();const row={revision:1,status:'confirmed',schedule_mode:'date',title:'T',start_date:'2099-02-30',end_date:'2099-03-01',starts_at:null,ends_at:null,timezone:'UTC',google_event_url:'https://www.google.com/calendar/test',organizer_email:'Synthetic@example.test'};const session={client:{rpc:async()=>({data:row,error:null})},user:{id}};await assert.rejects(()=>runtime.loadStatus(session,id));row.start_date='2099-02-28';const x=await runtime.loadStatus(session,id);assert.equal(x.startDate,row.start_date);assert.ok(!JSON.stringify(x).includes('@'));});
test('runtime RPC binding and ETag adapter use trusted parameters',async()=>{const {createDateConfirmationRuntime}=await jiti.import('../src/features/when-we-meet/date-confirmation-runtime.ts');const calls=[],runtime=createDateConfirmationRuntime({patchEvent:async(...args)=>{calls.push(args);},fetcher:async()=>Response.json({})});const session={client:{rpc:async(name,args)=>{calls.push({name,args});return {data:'reserved',error:null};}},user:{id}};const valid={roomId:id,revision:2,title:'T',startDate:'2099-01-01',endDate:'2099-01-02',recipients:[{userId:id,email:'Synthetic@example.test',optional:true}],excluded:[]};await runtime.reserve(session,'update',valid,'event123','a'.repeat(64));assert.deepEqual(calls[0].args,{p_room_id:id,p_revision:2,p_payload_hash:'a'.repeat(64),p_title:'T',p_start_date:'2099-01-01',p_end_date:'2099-01-02',p_recipient_ids:[id],p_excluded_ids:[],p_optional_ids:[id]});await runtime.patchEvent(session,'synthetic','event123',{sequence:2},'protected');assert.equal(calls[1][0],'synthetic');assert.deepEqual(calls[1][4],{etag:'protected'});});
