import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const source=()=>readFileSync(new URL('../src/features/when-we-meet/ConfirmationPanel.tsx',import.meta.url),'utf8');
test('confirmation UI requires explicit review and send callbacks, without fetch',()=>{const s=source();assert.match(s,/onConfirm:/);assert.match(s,/onConnectCalendar:/);assert.match(s,/Confirm &amp; send invitations/);assert.doesNotMatch(s,/\bfetch\s*\(/);});
test('recipient exclusions and missing addresses are reviewed',()=>{const s=source();assert.match(s,/excludedIds/);assert.match(s,/Missing email/);assert.match(s,/Not responded/);assert.match(s,/Unavailable/);});
const weekly=()=>readFileSync(new URL('../src/features/when-we-meet/WeeklyAvailability.tsx',import.meta.url),'utf8');
const panelCss=()=>readFileSync(new URL('../src/features/when-we-meet/confirmation-panel.css',import.meta.url),'utf8');
test('the confirm calendar is the compact Everyone calendar, not a separate count grid',()=>{const s=source();assert.match(s,/<WeeklyAvailability [^>]*selection=\{selection\}\/>/);assert.doesNotMatch(s,/wwm-confirm-grid|wwm-confirm-cell|available:number/);assert.doesNotMatch(panelCss(),/wwm-confirm-grid|wwm-confirm-cell/);
 const w=weekly();assert.match(w,/compact=compactChoice\|\|Boolean\(selection\)/);assert.match(w,/\{!selection&&readOnly&&<div className="wwm-segmented"/);assert.match(w,/readOnly=everyoneView\|\|Boolean\(selection\)/);});
test('selection cells name date, time and N of M members; rails are visual only while selecting',()=>{const w=weekly();
 assert.match(w,/aria-label=\{`\$\{formatCraftDate\(slot\.date\)\} \$\{span\(slot\.id,endOf\(slot\.id\)\)\}, \$\{projection\.countById\[slot\.id\]\?\?0\} of \$\{selection\.memberCount\} available`\}/);
 assert.match(w,/data-analytics-label=\{ANALYTICS_ELEMENTS\.CONFIRM_CELL\}/);assert.match(w,/aria-hidden=\{selecting\|\|undefined\}/);assert.match(w,/tabIndex=\{selecting\?-1:undefined\}/);
 assert.match(w,/gesture\.current\.down\('touch'/);assert.match(w,/if\(e\.key==='Enter'\|\|e\.key===' '\)\{e\.preventDefault\(\);tap\(slot\)\}/);});
test('calendar and fields edit one selection and the proposal carries the selected slot ids',()=>{const s=source();assert.match(s,/setRange\(fieldsRange\(slots,next\)\)/);assert.match(s,/const fields=rangeFields\(slots,next\)/);assert.match(s,/startId:range\.startId,endId:range\.endId/);assert.match(s,/onChange:busy\?undefined:selectRange/);assert.match(s,/rangeLabel:'Confirmed'/);});
